# Generated by Django 4.2.16 on 2025-05-26 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='author_profiles/')),
                ('info', models.TextField(blank=True, null=True)),
                ('works', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('isbn13', models.CharField(max_length=13)),
                ('description', models.TextField(blank=True)),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=50)),
                ('cover', models.URLField()),
                ('link', models.URLField()),
                ('customer_review_rank', models.FloatField(blank=True)),
                ('best_duration', models.TextField(blank=True)),
                ('best_rank', models.IntegerField(blank=True)),
                ('custom_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.customcategory')),
            ],
        ),
    ]
